let CASES = {
    'aabo': '二顶一',
    'obaa': '二顶一',
    'oaab': '二顶一',
    'baao': '二顶一',
    'aabb': '二顶二',
    'bbaa': '二顶二',
    'abbb': '一串三',
    'bbba': '一串三',
    'abba': '两夹沟',
    'baab': '两撑乎',
    'abao': '一夹沟',
    'oaba': '一夹沟',
    'babo': '一撑乎',
    'obab': '一撑乎',
};